### ISSUE TITLE
Documentation: back button broken on anchor usage (desktop)

### ISSUE THREAD

**Issue by venning** [lodash/lodash#1076]
*(Let me know if the documentation things I'm bringing up are getting too much.)*

In trying to mock up some changes to the presentation of `iteratee` and `predicate` information, I wanted to address something that's been driving me up the wall:  On desktop, when you are reading one part of the documentation and then click a link to another function, you can't use the Back button to return to what you were just reading.

**Example:** [go here](https://lodash.com/docs#forEach), click on the link in the function's description to `_.forIn` or `_.forOwn` and then click Back.  Nothing happens.  This presents for me on Firefox, Chrome, Safari, and IE 10.  Due to the media queries present, this does not present on mobile, or likely any viewport narrower than 960px.

This breaks normal browser behavior and can be frustrating to someone just learning lodash.  You see a link, try to figure out what it means, then go ba...wait...what was I looking at again?  Expected behavior would be something like clicking an inline link to a footnote on Wikipedia, then returning to your place with the Back button.

The underlying problem is that (on desktop) the `doc-container` is a scrolling div, which the browser can't reset the position of; I'm assuming that it can only reset the position of `body` when going back.  I would like to propose some CSS to fix this that handles the markup in a way that respects the semantics of the page while laying out `position` differently.

[See here for a live example](http://lodash-docs-work.s3-website-us-east-1.amazonaws.com/docs/) of the proposed fix.  The actual [changed CSS file is here](http://lodash-docs-work.s3-website-us-east-1.amazonaws.com/_css/main.css).  You will find four references to `@venning` in the comments.  I can explain the thinking for those changes a little more if you'd like, but this is already a lot of prose for a small issue.

There should be no visual difference in this fix when rendered, except that this positions the main scrollbar a little more naturally across the entire height of the page instead of being a little cut off at the top; "naturally" being a personal preference.  Also, there will be purple blur under the chrome when scrolling in Safari but, again, that should feel natural.

I feel like I'm missing some edge case, so let me know if anything looks wonky.

**Comment by jdalton** [comment]
Did you make any changes to the html or is it all style changes?

**Comment by venning** [comment]
Sorry, I should have specified.  Style only.

**Comment by jdalton** [comment]
This breaks [this](https://github.com/d10/lodash-docs-experiment/issues/4).

**Comment by d10** [comment]
I’ll try to take a look at the styles again.

**Comment by venning** [comment]
@jdalton I'm not sure what you're saying is broken.

If it's the "T" links, those have never worked for me.

If it's the "S" links, then Yeah, there's an offset now.  Good catch.  I'll have a fix in a bit.

**Comment by jdalton** [comment]
> If it's the "#" links, then Yeah, there's an offset now.  Good catch.  I'll have a fix in a bit.

Yap those.

**Comment by venning** [comment]
Okay I fixed it in [the example](http://lodash-docs-work.s3-website-us-east-1.amazonaws.com/docs/).  I needed to add one rule set, taken from [this SO answer](http://stackoverflow.com/a/13184714/270949).  It needs to be in the media query to not look wrong on mobile.  Look for an additional `@venning` comment, [line 320 of the CSS](http://lodash-docs-work.s3-website-us-east-1.amazonaws.com/_css/main.css).  No markup changes.

**Comment by jdalton** [comment]
Can you mark a clear beginning and end comment of changes. I've tried copying them over and not getting the same result.

**Comment by venning** [comment]
It would help if I could see the CSS/SASS/LESS file that you're working with.  Can you paste that in a gist or something so that I can just make the edits there?  I'm working off a pretty-printed version of the site's minified `main.css` so there's probably something else funky.

If not, I'll work on showing them more clearly...give me a minute.

**Comment by venning** [comment]
Also, I'm sorry about that, I completely forgot that I was working with a different file than you.

**Comment by venning** [comment]
*Working entirely within the existing media query* `@media (min-width: 960px)` I have done the following:

I have added the following entire two blocks:
```CSS
#docs h1 {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    background-color: #fff;
    z-index: 1;
}
#docs h3 a {
    display: block;
    position: relative;
    top: -4em; /* equal to negative of (.doc-container padding-top) + (h3 margin-top) */
    visibility: hidden;
}
```

I also am **starting** with the following block:
```CSS
#docs .doc-container {
    background: #fff;
    bottom: 0;
    position: fixed;
    overflow-y: scroll;
    overflow-x: hidden;
    right: 0;
    top: 3.5em;
    width: 80%;
    -webkit-overflow-scrolling: touch
}
```
Which I have **modified** to look like this:
```CSS
#docs .doc-container {
    background: #fff;
    width: 80%;
    margin-left: 20%;
    padding-top: 3.5em;
}
```
Hopefully this matches up to what you're working with.
